### ISSUE TITLE
Consider using `application/json` rather than `application/x-www-form-urlencoded` in the `id_assertion_endpoint`

### ISSUE THREAD

**Issue by samuelgoto** [w3c-fedid/FedCM#644]
Forking something orthogonal from this thread https://github.com/w3c-fedid/continuation/issues/2 so that we can look in isolation, rather than in conjunction with the original issue

**Comment by panva** [comment]
@samuelgoto I believe the registered JSON content-type would be `application/json`?

**Comment by bc-pi** [comment]
As is often the case, @panva is correct*. 

* my assessment of correctness is based on my own research at https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by elf-pavlik** [comment]
For completeness, I'll copy the response from @cbiesinger 

> It is possible, although there are two/three downsides to that proposal:
> * Sending the body as JSON means we trigger a CORS preflight (this isn't necessarily a problem, but makes things a bit more complicated and adds latency)
> * There's a few IDPs who already adopted FedCM which would need to update their code
> * JSON post bodies are relatively unusual
>
> But yeah we could go that route. The easiest way to do that might be to require IDPs to opt in to that when they are ready and eventually remove support for urlencoded.


I believe @gffletch mentioned [OIDC - Passing Request Parameters as JWTs](https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests), where the Request Object is compatible with [OAuth 2.0 Authorization Framework: JWT-Secured Authorization Request](https://www.rfc-editor.org/rfc/rfc9101.html).

Looking at [OAuth 2.0 Pushed Authorization Requests](https://www.rfc-editor.org/rfc/rfc9126.html) the POST also uses `application/x-www-form-urlencoded`, so using `application/json` would indeed be diverging from OAuth.

The expired [OAuth 2.0 JSON Request](https://datatracker.ietf.org/doc/html/draft-richer-oauth-json-request-00) draft also seems to confirm that. 

This issue could be resolved by simply leaving the request as `application/x-www-form-urlencoded` since it follows OAuth practice.

It might be worth looking at the OIDC Request Object, JAR, and PAR usage of JWT compared to the simple JSON string proposed in #556. Any potential discussion would probably belong to that issue.

**Comment by elf-pavlik** [comment]
This was discussed during the meeting reviewing #661 
I think this issue can be closed
