### ISSUE TITLE
Missing Attack Scenario: User Agent colluding with an IDP or RP

### ISSUE THREAD

**Issue by kdeqc** [w3c-fedid/FedCM#86]
I think it's also important to include the UA as a part of the IDP and RP identity exchange since it is a part of the process, and could theoretically collude with either party.  Similar to the issue I filed about the scenario where the IDP and RP are owned by the same entity, I would also specify when the UA is also owned by the same entity that owns the IDP or the RP (or both).  Again, it's not something that can necessarily be mitigated against, but I think it's important to address it because there is the potential for risk there.

**Comment by samuelgoto** [comment]
The whole web platform trust model is based on the idea that the browser is the user's agent, so when you throw out that assumption, a lot of things break.

Whether it is a malicious UA or a compromised UA, those fall out of the threat model because that's game over for everything that you are going to do going forward in your UA.

Here is a similar question that comes up often in other parts:

https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/faq.md#Why-arent-physically_local-attacks-in-Chromes-threat-model

> We consider these attacks outside Chrome's threat model, because there is no way for Chrome (or any application) to defend against a malicious user who has managed to log into your device as you, or who can run software with the privileges of your operating system user account. Such an attacker can modify executables and DLLs, change environment variables like PATH, change configuration files, read any data your user account owns, email it to themselves, and so on. Such an attacker has total control over your device, and nothing Chrome can do would provide a serious guarantee of defense. This problem is not special to Chrome ­— all applications must trust the physically-local user.

On

> Similar to the issue I filed about the scenario where the IDP and RP are owned by the same entity, I would also specify when the UA is also owned by the same entity that owns the IDP or the RP (or both). 

I think that's a slightly different threat and I commented there directly.

**Comment by npm1** [comment]
Closing per Sam's reply above. This is outside of our threat model
